api_platform:
    title: 'Synkro API'
    description: 'Collaborative project management API'
    version: '1.0.0'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header