parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Domain/ValueObject/'
            - '../src/Kernel.php'

    # Binding des interfaces vers les implémentations Doctrine
    App\Domain\Repository\UserRepositoryInterface:
        class: App\Infrastructure\Persistence\DoctrineUserRepository

    App\Domain\Repository\ProjectRepositoryInterface:
        class: App\Infrastructure\Persistence\DoctrineProjectRepository

    App\Domain\Repository\TaskRepositoryInterface:
        class: App\Infrastructure\Persistence\DoctrineTaskRepository